services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    hostname: zookeeper
    networks:
     - confluent
    volumes:
      - ./zookeeper.sasl.jaas.conf:/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
      - ./kafka-0-creds:/etc/zookeeper/secrets
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
       -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
       -Dzookeeper.allowSaslFailedClients=false
       -Dzookeeper.requireClientAuthScheme=sasl
    ports:
      - 2181:2181

  kafka-0:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-0
    hostname: kafka-0
    depends_on:
      - zookeeper
    networks:
     - confluent
    ports:
      - 9092:9092
      - 9093:9093
      - 9091:9091
    volumes:
      #- data-kafka-0:/var/lib/kafka/data
      #- ./kafka-1-creds:/etc/kafka/jaas
      - ./kafka-0-creds:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
      # - ./kafka-0-cred/server.properties:/etc/kafka/server.properties
      - shared-data:/data
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: BOB://0.0.0.0:9091,PLAINTEXT://0.0.0.0:9092,SASL_SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: BOB://kafka-0:9091, PLAINTEXT://localhost:9092,SASL_SSL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BOB:PLAINTEXT, PLAINTEXT:PLAINTEXT, SASL_SSL:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_truststore_creds
      KAFKA_SSL_KEYSTORE_PASSWORD: your-password
      KAFKA_SSL_TRUSTSTORE_PASSWORD: your-password
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/config/kafka_server_jaas.conf"
      KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_ZOOKEEPER_SET_ACL: true
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: "User:admin;User:ANONYMOUS"
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_MESSAGE_MAX_BYTES: 469296129
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200


  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    depends_on:
      - zookeeper
    networks:
      confluent:
    ports:
      - 9094:9094
      - 9095:9095
      - 9096:9096
      #- "127.0.0.1:9094:9094"
    volumes:
      #- data-kafka-1:/var/lib/kafka/data
      #- ./kafka-2-creds:/etc/kafka/jaas
      - ./kafka-1-creds:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
      # - ./kafka-1-cred/server.properties:/etc/kafka/server.properties
      - shared-data:/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: BOB://0.0.0.0:9096,PLAINTEXT://0.0.0.0:9094,SASL_SSL://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: BOB://kafka-1:9096,PLAINTEXT://localhost:9094,SASL_SSL://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BOB:PLAINTEXT, PLAINTEXT:PLAINTEXT, SASL_SSL:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_truststore_creds
      KAFKA_SSL_KEYSTORE_PASSWORD: your-password
      KAFKA_SSL_TRUSTSTORE_PASSWORD: your-password
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/config/kafka_server_jaas.conf"
      KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_ZOOKEEPER_SET_ACL: true
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: "User:admin;User:ANONYMOUS"
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_MESSAGE_MAX_BYTES: 469296129
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200


  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    depends_on:
      - zookeeper
    networks:
      confluent:
    ports:
      - 9097:9097
      - 9098:9098
    volumes:
      #- data-kafka-2:/var/lib/kafka/data
      #- ./kafka-3-creds:/etc/kafka/jaas
      - ./kafka-2-creds:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
      # - ./kafka-2-cred/server.properties:/etc/kafka/server.properties
      - shared-data:/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: BOB://0.0.0.0:9099,PLAINTEXT://0.0.0.0:9097,SASL_SSL://0.0.0.0:9098
      KAFKA_ADVERTISED_LISTENERS: BOB://kafka-2:9099,PLAINTEXT://localhost:9097,SASL_SSL://localhost:9098
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BOB:PLAINTEXT,PLAINTEXT:PLAINTEXT, SASL_SSL:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_truststore_creds
      KAFKA_SSL_KEYSTORE_PASSWORD: your-password
      KAFKA_SSL_TRUSTSTORE_PASSWORD: your-password
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/config/kafka_server_jaas.conf"
      KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_ZOOKEEPER_SET_ACL: true
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: "User:admin;User:ANONYMOUS"
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
     - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      confluent:

  broker2:
    image: confluentinc/cp-server:7.4.0
    hostname: broker2
    container_name: broker2
    depends_on:
     - zookeeper2
    ports:
     - "9083:9083"
     - "9102:9102"
    environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper2:2182'
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29093,PLAINTEXT_HOST://localhost:9083
     KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
     KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     KAFKA_JMX_PORT: 9102
     KAFKA_JMX_HOSTNAME: localhost
     CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker2:29093
     CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
     CONFLUENT_METRICS_ENABLE: 'true'
     CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      confluent:
    
  kafka-connect:
    build:
      context: ./kafka-connect
    ports:
      - "8083:8083"
      - "9875:9875"
      - "9876:9876"
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka-0:9093,kafka-1:9095,kafka-2:9098'
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'kafka-connect'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'localhost'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-config-storage'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offset-storage'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status-storage'
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      CONNECT_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka.keystore.pkcs12
      CONNECT_SSL_KEYSTORE_PASSWORD: your-password
      CONNECT_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka.truststore.jks
      CONNECT_SSL_TRUSTSTORE_PASSWORD: your-password
      CONNECT_SSL_KEYSTORE_TYPE: PKCS12
      CONNECT_SSL_TRUSTSTORE_TYPE: JKS
      CONNECT_SSL_KEYSTORE_FILENAME: kafka.kafka.keystore.pkcs12
      CONNECT_SSL_KEYSTORE_CREDENTIALS: kafka_keystore_creds
      CONNECT_SSL_KEY_CREDENTIALS: kafka_sslkey_creds
      CONNECT_SSL_TRUSTSTORE_FILENAME: kafka.kafka.truststore.jks
      CONNECT_SSL_TRUSTSTORE_CREDENTIALS: kafka_truststore_creds
      CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
        username=\"alice\" \
        password=\"alice-secret\";"
    volumes:
      - ./confluent-hub-components/:/etc/kafka-connect/jars
      - ./kafka-0-creds:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
    networks:
      confluent:

  hadoop-namenode:
    image: apache/hadoop:3.4.1
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    user: "root"
    restart: always
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "1.0"   # Ограничение использования CPU
          memory: "2g"  # Ограничение использования RAM
    shm_size: 10G
    ports:
      - "9870:9870"  # HTTP-порт для Web UI HDFS NameNode
      - "9000:9000"  # RPC порт для запросов к NameNode
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site-namenode.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./namenode_entrypoint.sh:/namenode_entrypoint.sh
    entrypoint: ["/bin/bash", "/namenode_entrypoint.sh"]
    command: ["hdfs", "namenode"]
    networks:
      confluent:

  hadoop-datanode-1:
   image: apache/hadoop:3.4.1
   container_name: hadoop-datanode-1
   hostname: hadoop-datanode-1
   user: "root"
   restart: always
   platform: linux/amd64
   deploy:
     resources:
       limits:
         cpus: "1.0"   # Ограничение использования CPU
         memory: "2g"  # Ограничение использования RAM
   shm_size: 10G
   depends_on:
     - hadoop-namenode
   ports:
     - "9864:9864"  # HTTP-порт для Web UI DataNode №1
     - "9970:9970"  # RPC порт для запросов от NameNode
   volumes:
     - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
     - ./config/hdfs-site-datanode-1.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
     - ./datanode_entrypoint.sh:/datanode_entrypoint.sh
   entrypoint: ["/bin/bash", "/datanode_entrypoint.sh"]
   command: ["hdfs", "datanode"]
   networks:
      confluent:

  hadoop-datanode-2:
   image: apache/hadoop:3.4.1
   container_name: hadoop-datanode-2
   hostname: hadoop-datanode-2
   user: "root"
   restart: always
   platform: linux/amd64
   deploy:
     resources:
       limits:
         cpus: "1.0"   # Ограничение использования CPU
         memory: "2g"  # Ограничение использования RAM
   shm_size: 10G
   depends_on:
     - hadoop-namenode
   ports:
     - "9865:9865"  # HTTP-порт для Web UI DataNode №2
     - "9971:9971"  # RPC порт для запросов от NameNode
   volumes:
     - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
     - ./config/hdfs-site-datanode-2.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
     - ./datanode_entrypoint.sh:/datanode_entrypoint.sh
   entrypoint: ["/bin/bash", "/datanode_entrypoint.sh"]
   command: ["hdfs", "datanode"]
   networks:
      confluent:

  hadoop-datanode-3:
   image: apache/hadoop:3.4.1
   container_name: hadoop-datanode-3
   hostname: hadoop-datanode-3
   user: "root"
   restart: always
   platform: linux/amd64
   deploy:
     resources:
       limits:
         cpus: "1.0"   # Ограничение использования CPU
         memory: "2g"  # Ограничение использования RAM
   shm_size: 10G
   depends_on:
     - hadoop-namenode
   ports:
     - "9866:9866"  # HTTP-порт для Web UI DataNode №3
     - "9972:9972"  # RPC порт для запросов от NameNode
   volumes:
     - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
     - ./config/hdfs-site-datanode-3.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
     - ./datanode_entrypoint.sh:/datanode_entrypoint.sh
   entrypoint: ["/bin/bash", "/datanode_entrypoint.sh"]
   command: ["hdfs", "datanode"]
   networks:
      confluent:

volumes:
  shared-data:

networks:
 confluent:
   driver: bridge